### ISSUE TITLE
Unreadable Discord custom status text on a bright theme.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [GibbuBDStuff/MinimalCord#1]
With a couple of plugins and stuff :
![Screenshot_20200314_144056](https://user-images.githubusercontent.com/13170204/76683140-a18f3300-65f9-11ea-9573-629d2258a1a1.png)
Theme only :
![image](https://user-images.githubusercontent.com/13170204/76683241-88d34d00-65fa-11ea-85eb-b8a906f89961.png)

**Comment by PoorPocketsMcNewHold** [comment]
Oh, I shouldn’t really select the text in those screenshots, but that text color is white, on the white theme, making it completely unreadable.
This affect other plugins like BadgesEverywhere (Strangely not working on that preview), and CreationDate (Showned on top of the Custom Status).
![Peek 14-03-2020 15-04](https://user-images.githubusercontent.com/13170204/76683558-fbddc300-65fc-11ea-87db-e98d93e34e10.gif)

**Comment by PoorPocketsMcNewHold** [comment]
Here´s a screenshot with the BadgeEverywhere working again. This issue seems to make those dissapear aswell (Despite those beings icons).
![image](https://user-images.githubusercontent.com/13170204/76700013-f63eb680-66aa-11ea-8ee1-d855878f32c8.png)

**Comment by Gibbu** [comment]
I'll check it out when I get home

**Comment by Gibbu** [comment]
Should be fixed now

**Comment by PoorPocketsMcNewHold** [comment]
![image](https://user-images.githubusercontent.com/13170204/76761947-a803e300-6790-11ea-9639-5baa8fb12355.png)
Yep. Thanks !
